name: Report Filter Issues
description: file a filterlist issue
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
          required: true
        - label: I am running the latest version of uBlock Origin
          required: true
    
  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label: uBO is the only extension
          required: true
        - label: uBO with default lists/settings
          required: true
        - label: using a new, unmodified browser profile
          required: true

  - type: textarea
    attributes:
      label: URL(s) where the issue occurs
      description: |
        At least one URL for a web page where the clearly described issue occurs is **mandatory**. 
        The backticks (`) surrounding the URLs are important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.
      placeholder: |
        `https://example.com`
        `https://example.org`
        `https://example.net`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **adult material**.
    validations:
      required: false

  - type: input
    attributes:
      label: uBlock Origin version
    validations:
      required: true

  - type: input
    attributes:
      label: Browser name and version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Settings
      description: List all the changes you've made to uBO's default settings here
      placeholder: |
        - Change 1
        - Change 2
        - Change 3
    validations:
      required: true  

  - type: textarea
    attributes:
      label: Notes
      description: |
        Please investigate the issues you report -- this prevents burdening other volunteers. 
        This is especially true for issues arising from settings which are very different from default ones.
      placeholder: Write here the result of whatever investigation work you have done
    validations:
      required: false
