blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://old.reddit.com/r/uBlockOrigin/
    about: Answers to questions and other kinds of help support is provided on the subreddit r/uBlockOrigin
  - name: uBlock Origin issues
    url: https://github.com/uBlockOrigin/uBlock-issues/issues
    about: Issues about uBlock Origin itself
