blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://www.reddit.com/r/uBlockOrigin/
    about: For support, questions, or help, visit /r/uBlockOrigin.
  - name: uBlock Origin (uBO) Issues
    url: https://github.com/uBlockOrigin/uBlock-issues/issues
    about: Report any issues with uBO in the uBO issue tracker.
