name: Support Pane Filter Issue
description: "DO NOT MANUALLY SELECT THIS TEMPLATE. It's used by uBlock Origin (uBO)'s \"Support\" pane to auto-fill essential information to file a filter issue."
body:
  - type: markdown
    attributes:
      value: To avoid burdening **VOLUNTEERS** with invalid or duplicate reports, disregarding these steps **WILL** get your account blocked on this repository temporarily, then permanently, with repeated disregard for the template.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        **IMPORTANT:** Answer carefully and truthfully.
      options:
        - label: This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
          required: true
        - label: I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
          required: true
        - label: I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
          required: true
        - label: I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
          required: true
        - label: I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
          required: true
        - label: I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
          required: true
        - label: I am not using uBlock Origin along with other content blockers.
          required: true
        - label: I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
          required: true
        - label: I have verified that other extensions are not causing the issue.
          required: true
        - label: If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
          required: true
        - label: I did not answer truthfully to **ALL** the above checkboxes.
          required: false
          
  - type: textarea
    attributes:
      label: URL(s) where the issue occurs.
      description: |
        At least one URL is **MANDATORY** for an issue affecting a web page.
        Warn with **"NSFW"** where applicable.
      placeholder: |
        https://example.com
        https://example.org
        https://example.net
      render: yaml
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other extensions used
      description: List other extensions you are using along uBO (write _none_ if no other extensions). This information helps volunteers investigate issues.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) are **MANDATORY** for hard-to-describe visual issues.
        ðŸ”´ Post **LINKS** instead of inline images for screenshots containing **ADULT MATERIAL**. Disregarding this directive **WILL** get your account blocked. ðŸ”´
      value: |
        <details>
        <summary>Screenshot(s)</summary>

        <!-- Drag-and-drop screenshot here -->
        <!-- â¬‡ï¸  â¬‡ï¸  â¬‡ï¸ -->


        <!-- â¬†ï¸  â¬†ï¸  â¬†ï¸ -->

        </details>
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        If this section gets automatically filled by uBO, leave it alone.
    validations:
      required: true
