name: Popup Panel Specific Filter Issue
description: Use this template when reporting a filter issue from uBO's popup panel.
body:
  - type: markdown
    attributes:
      value: To avoid burdening **VOLUNTEERS** with invalid or duplicate reports, disregarding these steps **WILL** get your account blocked on this repository temporarily, then permanently, with repeated disregard for the template.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        **IMPORTANT:** Answer carefully and truthfully.
      options:
        - label: I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
          required: true
        - label: This is NOT a [YouTube](https://github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://github.com/uBlockOrigin/uAssets/issues/5184) report.
          required: true
        - label: I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
          required: true
        - label: I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
          required: true
        - label: I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
          required: true
        - label: I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
          required: true
        - label: I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
          required: true
        - label: I am not using uBlock Origin (uBO) along with other content blocker extensions.
          required: true
        - label: I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
          required: true
        - label: I did not answer truthfully to **ALL** the above checkpoints.
          required: false

  - type: textarea
    id: url_address_of_the_web_page
    attributes:
      label: URL address of the web page
      description: |
        Auto-filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    id: category
    attributes:
      label: Category
      description: |
        Auto-filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and concise description of this filter issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other extensions used
      description: List other extensions you are using along uBO (write _none_ if no other extensions). This information helps volunteers investigate issues.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) are **MANDATORY** for hard-to-describe visual issues.
        🔴 Post **LINKS** instead of inline images for screenshots containing **ADULT MATERIAL**. Disregarding this directive **WILL** get your account blocked. 🔴
      value: |
        <details>
        <summary>Screenshot(s)</summary>

        <!-- drag-and-drop screenshot here -->

        </details>
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Auto-filled by uBO, leave it alone.
    validations:
      required: true
