name: Report Specific Filter Issue From Popup Panel
description: |
  Use this template when reporting filter issue from uBO's popup panel.
body:
  - type: markdown
    attributes:
      value: |
        To avoid burdening **VOLUNTEERS** with invalid or duplicate reports, disrespecting these steps **WILL** result in your account being blocked on this repo (temporarily, then permanently with repeated disregard for the template).

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        **Important:** Answer carefully and truthfully
      options:
        - label: I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
          required: true
        - label: I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
          required: true
        - label: I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
          required: true
        - label: I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
          required: true
        - label: I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
          required: true
        - label: I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
          required: true
        - label: I did not open more than five (5) issues today, or I am a long time contributor to this repo
          required: true

  - type: textarea
    attributes:
      label: URL address of the web page
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Category
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **adult material**.
      value: |
        <details>
        <summary>Screenshot(s)</summary>
        
        <!-- drag-and-drop screenshot here -->
        
        </details>
    validations:
      required: false

  - type: textarea
    attributes:
      label: Configuration
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true  
