name: Update Easylist assets (hourly)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    if: github.repository_owner == 'uBlockOrigin'
    permissions:
      actions: write
      contents: write  # for Git to git push
    name: Update Easylist assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assemble Easylist assets
        run: |
          ./tools/make-easylist.sh

      - name: Commit changes, if any
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "github-actions bot"
            git config user.email "<>"
            git add -u thirdparties/
            git commit -m "Update Easylist assets"
            git pull --rebase origin master
            git push origin master
            gh workflow run main.yml
          fi
